{% set name = "spotipy" %}
{% set version = "2.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 29c60c8b99da1c4b9f0d722169bc31e624b8c07d7186b8eadd9c02e8d2d42cbf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests >=2.20.0
    - six >=1.10.0

test:
  imports:
    - spotipy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://spotipy.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A light weight Python library for the Spotify Web API
  doc_url: http://spotipy.readthedocs.org/
  dev_url: https://github.com/plamere/spotipy/

extra:
  recipe-maintainers:
    - captivus
